export const uiV2Tokens = {
  color: {
    primary: "var(--color-accent)",
    bg: "var(--color-bg)",
    fg: "var(--color-text)",
    border: "var(--color-border)",
    subtle: "var(--color-bg-subtle)",
    muted: "var(--color-text-muted)",
    success: "var(--color-success)",
    warning: "var(--color-warning)",
    danger: "var(--color-danger)",
    info: "var(--color-info)",
    roles: {
      success: {
        bg: "var(--color-status-current-bg)",
        fg: "var(--color-status-current-text)",
        border: "var(--color-status-current-border)",
        subtle: "var(--color-success-soft)",
        muted: "var(--color-text-muted)",
      },
      warning: {
        bg: "var(--color-status-warning-bg)",
        fg: "var(--color-status-warning-text)",
        border: "var(--color-status-warning-border)",
        subtle: "var(--color-warning-soft)",
        muted: "var(--color-text-muted)",
      },
      danger: {
        bg: "var(--color-status-danger-bg)",
        fg: "var(--color-status-danger-text)",
        border: "var(--color-status-danger-border)",
        subtle: "var(--color-danger-soft)",
        muted: "var(--color-text-muted)",
      },
      info: {
        bg: "var(--color-status-info-bg)",
        fg: "var(--color-status-info-text)",
        border: "var(--color-status-info-border)",
        subtle: "var(--color-info-soft)",
        muted: "var(--color-text-muted)",
      },
    },
  },
  type: {
    pageTitle: "24px/32px",
    sectionTitle: "18px/28px",
    body: "14px/20px",
    meta: "12px/16px",
  },
  spacing: [4, 8, 12, 16, 20, 24, 32, 40, 56],
  radius: {
    sm: 6,
    md: 8,
    lg: 12,
    pill: 999,
  },
  motion: {
    fast: "150ms ease-out",
    panel: "200ms ease-out",
  },
  elevation: {
    e0: "border only",
    e1: "var(--shadow-card)",
    e2: "var(--shadow-popover)",
  },
} as const;
